sudo: required

language: sh

before_install:
​    - sudo apt-get update -q
​    - export scversion="stable" # or "v0.4.7", or "latest"
​    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
​    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
​    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
​    - /usr/bin/shellcheck --version

script:
  - bash test.sh
  - bash exp04/bash/second.sh
  - bash exp04/bash/image.sh -h
  - bash exp04/bash/image.sh -i test1.jpg -o out1.jpg -q 60
  - bash exp04/bash/image.sh -i test1.jpg -o out2.jpg -q 60
  - bash exp04/bash/image.sh -i test2.png -o out3.png -q 70
  - bash exp04/bash/image.sh -i test1.jpg -o out4.jpg -w WATERMARK_TEST
  - bash exp04/bash/image.sh -i input -o output -p PRE
  - bash exp04/bash/image.sh -i input -o output -s POST

  - bash exp04/bash/web_log.sh

after_script:
  - /usr/bin/shellcheck test.sh
  - /usr/bin/shellcheck exp04/bash/*.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
​    on_success: never
